[package]
name = "ship-designer-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.8", default-features = false }
uflow = "0.6"
num_enum = "0.5"
thiserror = "1.0"